image: composer:2.0

pipelines:
  default:
    - step:
        name: Install Package
        caches:
          - composer
        script:
          - composer install
    - step: 
        name: Test
        script:
          - vendor/bin/phpunit --bootstrap vendor/autoload.php tests
