image: php:8.0

pipelines:
  default:
    - step:
        name: Install Package
        script:
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
    - step: 
        name: Test
        script:
          - vendor/bin/phpunit --bootstrap vendor/autoload.php tests