setup:
    options:
        # string
        - {
            key: 'key_1',
            type: 'Wvandenhaak\Configuration\Common\Value\Option\StringType',
        }

        # array
        - {
            key: 'key_2',
            type: 'Wvandenhaak\Configuration\Common\Value\Option\ArrayType',
            choices: [value_2_1, value_2_2, value_2_3, value_2_4],
            default: [value_2_2, value_2_4]
        }

        # boolean
        - {
            key: 'key_3',
            type: 'Wvandenhaak\Configuration\Common\Value\Option\BooleanType',
            default: false
        }

        # int
        - {
            key: 'key_4',
            type: 'Wvandenhaak\Configuration\Common\Value\Option\IntegerType',
        }

        # Custom class to retrieve option values from
        - {
            key: 'key_5',
            provider: 'Wvandenhaak\Configuration\Tests\data\classes\CustomOptionProvider'
        }

    groups:
        - { name: Group 1, keys: [key_1, key_2] }
        - { name: Group 2, keys: [key_3, key_4] }
        - { name: Group 3, keys: [ key_5] }