options: 
    # string
    - {
        key: 'key_1',
        value: 'value_1',
        type: 'IceCake\AppConfigurator\Common\Value\Option\StringType',
        default: null
    }

    # array
    - {
        key: 'key_2',
        value: [value_2_1, value_2_2, value_2_3, value_2_4],
        type: 'IceCake\AppConfigurator\Common\Value\Option\ArrayType',
        default: null
    }

    # boolean
    - {
        key: 'key_3',
        value: false,
        type: 'IceCake\AppConfigurator\Common\Value\Option\BooleanType',
        default: null
    }

    # int
    - {
        key: 'key_4',
        value: 12345,
        type: 'IceCake\AppConfigurator\Common\Value\Option\IntegerType',
        default: null
    }

groups:
    - {name: Group 1, keys: [key_1, key_2] }
    - {name: Group 2, keys: [key_3, key_4] }